XeroNetStandardApp/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Xero.NetStandard.OAuth2.Client;
using Xero.NetStandard.OAuth2.Config;
using Xero.NetStandard.OAuth2.Token;
using Microsoft.Extensions.Options;
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Xero.NetStandard.OAuth2.Models;
using System.Collections.Generic;

namespace XeroNetStandardApp.Controllers
{
  public class AuthorizationController : Controller
  {
    private readonly ILogger<AuthorizationController> _logger;
    private readonly IOptions<XeroConfiguration> XeroConfig;
    private readonly IHttpClientFactory httpClientFactory;

    // GET /Authorization/
    public AuthorizationController(IOptions<XeroConfiguration> XeroConfig, IHttpClientFactory httpClientFactory, ILogger<AuthorizationController> logger)
    {
      _logger = logger;
      this.XeroConfig = XeroConfig;
      this.httpClientFactory = httpClientFactory;
    }

    public IActionResult Index()
    {

      var client = new XeroClient(XeroConfig.Value, httpClientFactory);

      return Redirect(client.BuildLoginUri());
    }

    // GET /Authorization/Callback
    public async Task<ActionResult> Callback(string code, string state)
    {
      var client = new XeroClient(XeroConfig.Value, httpClientFactory);
      var xeroToken = (XeroOAuth2Token)await client.RequestXeroTokenAsync(code);

      List<Tenant> tenants = await client.GetConnectionsAsync(xeroToken);

      Tenant firstTenant = tenants[0];

      TokenUtilities.StoreToken(xeroToken);

      return RedirectToAction("Index", "OrganisationInfo");
    }

    // GET /Authorization/Disconnect
    public async Task<ActionResult> Disconnect()
    {      
      var client = new XeroClient(XeroConfig.Value, httpClientFactory);

      var xeroToken = TokenUtilities.GetStoredToken();
      var utcTimeNow = DateTime.UtcNow;

      if (utcTimeNow > xeroToken.ExpiresAtUtc)
      {
        xeroToken = (XeroOAuth2Token)await client.RefreshAccessTokenAsync(xeroToken);
        TokenUtilities.StoreToken(xeroToken);
      }

      string accessToken = xeroToken.AccessToken;
      Tenant xeroTenant = xeroToken.Tenants[0];

      await client.DeleteConnectionAsync(xeroToken, xeroTenant);

      TokenUtilities.DestroyToken();

      return RedirectToAction("Index", "Home");
    }
  }
}

XeroNetStandardApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using XeroNetStandardApp.Models;

namespace XeroNetStandardApp.Controllers
{
  public class HomeController : Controller
  {
    public IActionResult Index()
    {
      bool firstTimeConnection = TokenUtilities.TokenExists();

      return View(firstTimeConnection);
    }
    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

XeroNetStandardApp/Controllers/PayrollController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Model.PayrollAu;
using Xero.NetStandard.OAuth2.Token;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Config;
using Xero.NetStandard.OAuth2.Client;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Net.Http;

namespace XeroNetStandardApp.Controllers
{
  public class PayrollController : Controller
  {
    private readonly ILogger<AuthorizationController> _logger;
    private readonly IOptions<XeroConfiguration> XeroConfig;
    private readonly IHttpClientFactory httpClientFactory;

    public PayrollController(IOptions<XeroConfiguration> XeroConfig, IHttpClientFactory httpClientFactory, ILogger<AuthorizationController> logger)
    {
      _logger = logger;
      this.XeroConfig = XeroConfig;
      this.httpClientFactory = httpClientFactory;
    }

    // GET: /PayrollController/
    public async Task<ActionResult> Index()
    {
      var xeroToken = TokenUtilities.GetStoredToken();
      var utcTimeNow = DateTime.UtcNow;

      if (utcTimeNow > xeroToken.ExpiresAtUtc)
      {
        var client = new XeroClient(XeroConfig.Value, httpClientFactory);
        xeroToken = (XeroOAuth2Token)await client.RefreshAccessTokenAsync(xeroToken);
        TokenUtilities.StoreToken(xeroToken);
      }

      string accessToken = xeroToken.AccessToken;
      string xeroTenantId = xeroToken.Tenants[0].TenantId.ToString();

      var PayrollAUApi = new PayrollAuApi();
      var response = await PayrollAUApi.GetTimesheetsAsync(accessToken, xeroTenantId);

      var timesheet = response._Timesheets;

      return View(timesheet);
    }

    // GET: /Contacts#Create
    [HttpGet]
    public IActionResult Create()
    {
      return View();
    }

   }
}

XeroNetStandardApp/Views/Home/Index.cshtml
@model dynamic

@{
    ViewData["Title"] = "Home Page";
}

<div class=" col-12">
    @if (Model == false)
    {
        <p>
            <button onclick="location.href='@Url.Action("Index", "Authorization")'">Connect to Xero</button>
        </p>
    }
    else
    {
        <p> You are connected to your Xero organisation. Try the following operations:</p>

        <p> Accounting APIs: </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "Authorization")'">Reauthorize Xero</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Disconnect", "Authorization")'">Disconnect Xero</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "OrganisationInfo")'">Get Organisation Information</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "ContactsInfo")'">Get Contacts</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Create", "ContactsInfo")'">Create A Contact</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "InvoiceSync")'">Get Invoices</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Create", "InvoiceSync")'">Create An Invoice</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "BankTransactionsInfo")'">Get BankTransactions</button>
        </p>

        <p> AU Payroll Timesheets: </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "Payroll")'">Get AU Payroll Timesheets</button>
        </p>


        <p> Asset APIs: </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "AssetsInfo")'">Get Fixed Assets</button>
        </p>

        <p>
            <button onclick="location.href='@Url.Action("Create", "AssetsInfo")'">Create A Fixed Asset</button>
        </p>

        <p> Identity APIs: </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "IdentityInfo")'">Get Connections using Identity Api</button>
        </p>

        <p> AU Payroll APIs: </p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "EmployeesInfo")'">Get AU Payroll Employees</button>
        </p>

        @*<p>
            <button onclick="location.href='@Url.Action("Create", "EmployeesInfo")'">Create An AU Payroll Employee</button>
        </p>*@


    }

</div>